"""Render a one-page FNOL-style claim form with reportlab."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def write_claim_form(path: Path, claim: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(path), pagesize=letter)
    width, height = letter
    c.setTitle(f"ACME Mutual FNOL {claim['claim_id']}")

    c.setFillColorRGB(0.10, 0.16, 0.22)
    c.rect(0, height - 72, width, 72, fill=1, stroke=0)
    c.setFillColorRGB(0.49, 0.83, 0.78)
    c.setFont("Times-Bold", 18)
    c.drawString(36, height - 36, "ACME MUTUAL INSURANCE")
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Times-Roman", 11)
    c.drawRightString(width - 36, height - 34, "First Notice of Loss — Claim Form")
    c.setFillColorRGB(0.2, 0.2, 0.2)
    c.setFont("Times-Roman", 9)
    c.drawString(36, height - 56, "Specimen form for synthetic / training use only. Not a live policy document.")

    y = height - 100
    rows = [
        ("Claim ID", claim["claim_id"]),
        ("Policy number", claim["policy_number"]),
        ("Policy form", claim["policy_form"]),
        ("Line of business", claim["line_of_business"]),
        ("Named insured", claim["claimant"]["full_name"]),
        ("Email", claim["claimant"]["email"]),
        ("Phone", claim["claimant"]["phone"]),
        ("Incident type", claim["incident"]["incident_type"]),
        ("Peril", claim["peril"]),
        ("Date of loss", claim["incident"]["incident_date"]),
        ("Date reported", claim["incident"]["reported_date"]),
        (
            "Location",
            f"{claim['incident']['location']['street_address']}, "
            f"{claim['incident']['location']['city']}, "
            f"{claim['incident']['location']['state']} "
            f"{claim['incident']['location']['postal_code']}",
        ),
        ("Claimed amount", f"${claim['claimed_amount']['amount']} USD"),
        ("Third party", "Yes" if claim["incident"]["third_party_involved"] else "No"),
        ("Police report", claim["incident"].get("police_report_number") or "Not attached"),
    ]
    vehicle = claim["incident"].get("vehicle")
    if vehicle:
        rows.append(
            (
                "Vehicle",
                f"{vehicle.get('year')} {vehicle.get('make')} {vehicle.get('model')}  VIN {vehicle.get('vin')}",
            )
        )
        rows.append(("Odometer", str(vehicle.get("odometer") or "—")))

    c.setFont("Times-Bold", 10)
    for label, value in rows:
        c.setFont("Times-Bold", 9)
        c.drawString(36, y, f"{label}:")
        c.setFont("Times-Roman", 9)
        c.drawString(160, y, str(value)[:90])
        y -= 16

    y -= 8
    c.setFont("Times-Bold", 10)
    c.drawString(36, y, "Loss description")
    y -= 16
    c.setFont("Times-Roman", 9)
    text = c.beginText(36, y)
    text.setFont("Times-Roman", 9)
    for line in _wrap(claim["incident"]["description"], 95):
        text.textLine(line)
    c.drawText(text)

    c.setFont("Times-Roman", 8)
    c.drawString(36, 36, "ACME Mutual — PAP-CG-01 / HO3-CG-01 specimen. Generated by ClaimGuard.")
    c.showPage()
    c.save()


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        trial = f"{current} {word}".strip()
        if len(trial) > width:
            if current:
                lines.append(current)
            current = word
        else:
            current = trial
    if current:
        lines.append(current)
    return lines or [""]
