"""Pydantic contracts used at every agent and API boundary."""

from claimguard.schemas.common import (
    AgentName,
    ClaimGuardModel,
    ClaimStatus,
    CoverageStatus,
    CurrencyCode,
    DamageType,
    DocumentType,
    GeoLocation,
    IncidentType,
    Money,
    RetrievalSource,
    RiskTier,
    RoutingDecision,
    SeverityLevel,
)
from claimguard.schemas.damage import DamageAssessment, DetectedObject, PhotoFinding
from claimguard.schemas.fraud import (
    EntityGraphMatch,
    FraudRuleHit,
    FraudSignal,
    SimilarFraudCase,
)
from claimguard.schemas.graph import (
    AgentStep,
    ClaimState,
    ClaimStateUpdate,
    DocumentRef,
    GraphError,
    GraphState,
    ImageRef,
    IntakeAgentInput,
    empty_claim_state,
)
from claimguard.schemas.intake import (
    ClaimantProfile,
    ClaimDocumentRef,
    ClaimImageRef,
    ClaimIntake,
    ExtractedEntity,
    IncidentDetails,
    IntakeExtraction,
    VehicleInfo,
)
from claimguard.schemas.policy import CitedClause, PolicyDetermination
from claimguard.schemas.trace import AgentSpan, AgentTrace
from claimguard.schemas.verdict import MissingDocument, SettlementMemo, TriageVerdict

__all__ = [
    "AgentName",
    "AgentSpan",
    "AgentStep",
    "AgentTrace",
    "CitedClause",
    "ClaimDocumentRef",
    "ClaimGuardModel",
    "ClaimImageRef",
    "ClaimIntake",
    "ClaimState",
    "ClaimStateUpdate",
    "ClaimStatus",
    "ClaimantProfile",
    "CoverageStatus",
    "CurrencyCode",
    "DamageAssessment",
    "DamageType",
    "DetectedObject",
    "DocumentRef",
    "DocumentType",
    "EntityGraphMatch",
    "ExtractedEntity",
    "FraudRuleHit",
    "FraudSignal",
    "GeoLocation",
    "GraphError",
    "GraphState",
    "ImageRef",
    "IncidentDetails",
    "IncidentType",
    "IntakeAgentInput",
    "IntakeExtraction",
    "MissingDocument",
    "Money",
    "PhotoFinding",
    "PolicyDetermination",
    "RetrievalSource",
    "RiskTier",
    "RoutingDecision",
    "SettlementMemo",
    "SeverityLevel",
    "SimilarFraudCase",
    "TriageVerdict",
    "VehicleInfo",
    "empty_claim_state",
]
